-- Human QA ratings for generated assets. Run once in the Supabase SQL editor.
-- Additive + idempotent.
--
-- One row per generation (= one `outputs` scene image + its 1:1 `videos` clip).
-- The rubric dimensions live in the app config (single source of truth), so the
-- per-dimension results are stored as JSONB — adding/removing a rubric item
-- later means editing the config, NOT this schema.
--
--   image / video JSONB shape (mirrors the build spec's output_schema):
--     {
--       "gates":  { "<id>": { "result": "Pass|Fail", "auto_value": <num|str|null>, "disputed": false } },
--       "scores": { "<id>": 1..5 },
--       "notes":  { "<id>": "string|null" }
--     }
--
-- Context columns are SNAPSHOTS taken at rating time, so a rating stays
-- interpretable even if the source rows are later regenerated or deleted.

create table if not exists public.asset_ratings (
    id                bigint generated by default as identity primary key,
    tenant_id         uuid,                                  -- auto-stamped from the output (trigger)
    output_id         bigint not null unique
                          references public.outputs(id) on delete cascade,
    video_id          bigint references public.videos(id) on delete set null,
    persona_id        bigint,
    tiktok_account_id bigint,

    -- context snapshot
    scenario_id       text,
    scenario_title    text,
    image_prompt      text,        -- outputs.prompt_used (filled by n8n later)
    video_script      text,        -- videos.prompt_used / dialogue
    image_storage_url text,
    video_storage_url text,

    -- the rating itself
    rater_id          text,                                   -- who rated (admin/tenant user)
    asset_triage      text,                                   -- 'Accept' | 'Reject' | 'Flag'
    image             jsonb not null default '{}'::jsonb,     -- { gates, scores, notes }
    video             jsonb not null default '{}'::jsonb,     -- { gates, scores, notes }
    image_rated       boolean not null default false,
    video_rated       boolean not null default false,
    rubric_version    text,                                   -- which config version produced this

    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

create index if not exists idx_asset_ratings_tenant   on public.asset_ratings(tenant_id);
create index if not exists idx_asset_ratings_video    on public.asset_ratings(video_id);
create index if not exists idx_asset_ratings_scenario on public.asset_ratings(scenario_id);
create index if not exists idx_asset_ratings_triage   on public.asset_ratings(asset_triage);

-- Auto-stamp tenant_id from the rated output (keeps it 100% tenant-scoped).
create or replace function public.set_asset_rating_tenant() returns trigger as $$
begin
    select o.tenant_id into new.tenant_id from public.outputs o where o.id = new.output_id;
    return new;
end; $$ language plpgsql;

drop trigger if exists trg_asset_rating_tenant on public.asset_ratings;
create trigger trg_asset_rating_tenant before insert or update on public.asset_ratings
    for each row execute function public.set_asset_rating_tenant();

-- MVP posture (match the rest of the schema): RLS off + grants.
alter table public.asset_ratings disable row level security;
grant all on public.asset_ratings to anon, authenticated, service_role;

-- Read a tenant's ratings:
--   select * from public.asset_ratings where tenant_id = '<tenant uid>';
