-- Impersonation audit log. Run once in the Supabase SQL editor. Additive.
--
-- Every time the super admin opens a tenant's interface ("Page" / view-as), we
-- record an event. Accountability for viewing customer data — an enterprise
-- requirement. The actor is 'super_admin' for now (hardcoded login); once the
-- super admin becomes a real auth user it will store that uid instead.

create table if not exists public.impersonation_events (
    id           bigint generated by default as identity primary key,
    actor        text        not null default 'super_admin',
    tenant_id    uuid        not null,
    tenant_name  text,
    tenant_email text,
    created_at   timestamptz not null default now()
);

create index if not exists idx_impersonation_events_created
    on public.impersonation_events(created_at desc);
create index if not exists idx_impersonation_events_tenant
    on public.impersonation_events(tenant_id);

-- MVP posture (match the rest of the schema): RLS off + grant to the app roles.
-- Without these grants the publishable key gets "permission denied".
alter table public.impersonation_events disable row level security;
grant all on public.impersonation_events to anon, authenticated, service_role;
