-- Multitenancy. Run once in the Supabase SQL editor.
--
-- Model: each signed-up MEMBER is a tenant; tenant_id = their auth.users.id.
-- The hardcoded super-admin is NOT a tenant — its rows have tenant_id = NULL
-- and the app applies no tenant filter for admin (admin sees everything, as
-- before). Members only ever see rows where tenant_id = their id.
--
-- ⚠️ Isolation is enforced in the frontend queries (RLS stays disabled to keep
-- the anon-key admin path working). For production-grade isolation, move admin
-- to a real auth/service path and add RLS policies keyed on auth.uid().

-- 1) Scope the accounts table. NULL = admin/global (unchanged behavior).
alter table public.tiktok_accounts
    add column if not exists tenant_id uuid;
create index if not exists idx_tiktok_accounts_tenant
    on public.tiktok_accounts(tenant_id);

-- 2) Per-tenant profile: API keys, briefings, and onboarding status.
create table if not exists public.tenant_profiles (
    tenant_id         uuid primary key,          -- = auth.users.id
    name              text,
    email             text,
    fal_api_key       text,
    anthropic_api_key text,
    product_briefing  text,
    company_briefing  text,
    onboarded         boolean not null default false,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

-- 3) Per-tenant uploaded images.
create table if not exists public.tenant_images (
    id          bigint generated by default as identity primary key,
    tenant_id   uuid not null,
    storage_url text not null,
    file_name   text,
    created_at  timestamptz not null default now()
);
create index if not exists idx_tenant_images_tenant
    on public.tenant_images(tenant_id);

-- 4) Public bucket for tenant image uploads (browser uploads directly).
insert into storage.buckets (id, name, public)
values ('tenant-images', 'tenant-images', true)
on conflict (id) do update set public = true;

do $$
begin
    if not exists (select 1 from pg_policies
        where schemaname='storage' and tablename='objects'
          and policyname='Public read tenant-images') then
        create policy "Public read tenant-images"
            on storage.objects for select to public
            using (bucket_id = 'tenant-images');
    end if;
    if not exists (select 1 from pg_policies
        where schemaname='storage' and tablename='objects'
          and policyname='Anyone upload tenant-images') then
        create policy "Anyone upload tenant-images"
            on storage.objects for insert to anon, authenticated
            with check (bucket_id = 'tenant-images');
    end if;
end $$;

-- 5) MVP posture (match the rest of the schema).
alter table public.tenant_profiles disable row level security;
alter table public.tenant_images   disable row level security;
grant all on public.tenant_profiles to anon, authenticated, service_role;
grant all on public.tenant_images   to anon, authenticated, service_role;

-- ───────────────────────────────────────────────────────────────────────────
-- Check later:
--   select tenant_id, name, email, onboarded, updated_at from public.tenant_profiles;
--   select tenant_id, count(*) from public.tenant_images group by tenant_id;
--   select tenant_id, count(*) from public.tiktok_accounts group by tenant_id;
-- ───────────────────────────────────────────────────────────────────────────
