-- TikTok auth + posting tables.
--
-- These two tables exist on the LIVE database but were never captured in a
-- SQL file in this repo (created directly / by the posting feature). This file
-- reconstructs them from the live schema so a fresh database (e.g. the dev
-- project) is a faithful copy. Run once in the Supabase SQL editor.
--
-- Reconstructed 2026-06-02 from information_schema on the live project.
--
--   tiktok_auth   : OAuth tokens per TikTok account (1:1 with tiktok_accounts)
--   tiktok_posts  : one row per published video (1:1 with videos)

-- ----------------------------------------------------------------------------
-- tiktok_auth  -  stored TikTok OAuth credentials, one per account
-- ----------------------------------------------------------------------------
create table if not exists public.tiktok_auth (
    tiktok_account_id bigint      not null
        primary key
        references public.tiktok_accounts(id),
    access_token      text        not null,
    refresh_token     text        not null,
    expires_at        timestamptz not null,
    open_id           text        not null,
    scope             text,
    updated_at        timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- tiktok_posts  -  one row per published video
-- ----------------------------------------------------------------------------
create table if not exists public.tiktok_posts (
    id                bigint generated by default as identity primary key,
    video_id          bigint      not null unique
        references public.videos(id),
    tiktok_account_id bigint      not null
        references public.tiktok_accounts(id),
    publish_id        text,
    status            text        not null,
    tiktok_post_url   text,
    error_reason      text,
    posted_at         timestamptz,
    created_at        timestamptz default now()
);
