-- ============================================================================
--  ALLUVI UGC Pipeline  -  Supabase / PostgreSQL schema
--  Complete, importable DDL for a fresh database.
--
--  Run top-to-bottom in the Supabase SQL editor, or:
--    psql "<connection-string>" -f supabase_schema.sql
--
--  Tables are created parent-first so foreign keys resolve cleanly:
--    tiktok_accounts  ->  personas  ->  outputs  ->  videos
-- ============================================================================

-- Optional: run on a clean database. Uncomment to drop existing tables first.
-- DROP TABLE IF EXISTS public.videos          CASCADE;
-- DROP TABLE IF EXISTS public.outputs         CASCADE;
-- DROP TABLE IF EXISTS public.personas        CASCADE;
-- DROP TABLE IF EXISTS public.tiktok_accounts CASCADE;


-- ----------------------------------------------------------------------------
-- 1. tiktok_accounts  -  the INPUT table (the only table humans fill in)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tiktok_accounts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiktok_id   text        NOT NULL UNIQUE,            -- TikTok handle, unique
    name        text        NOT NULL,
    gender      text        NOT NULL,                   -- 'female' / 'male'
    country     text        NOT NULL,                   -- drives look + language
    age         integer     NOT NULL CHECK (age >= 0 AND age <= 120),
    language    text        NOT NULL,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now()
);


-- ----------------------------------------------------------------------------
-- 2. personas  -  Phase A output: one generated AI portrait per account
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.personas (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiktok_account_id  bigint  NOT NULL UNIQUE
                       REFERENCES public.tiktok_accounts(id),
    drive_file_id      text,                            -- Drive id of the portrait
    drive_url          text,
    prompt_used        text,
    status             text        DEFAULT 'done',
    created_at         timestamptz DEFAULT now()
);


-- ----------------------------------------------------------------------------
-- 3. outputs  -  Phase B output: scene images (persona x scenario)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.outputs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id      bigint  NOT NULL REFERENCES public.personas(id),
    scenario_id     text    NOT NULL,                   -- which of the 30 scenarios
    scenario_title  text,
    drive_file_id   text,                               -- Drive id of the scene image
    drive_url       text,
    qc_status       text,                               -- 'pass' / 'skipped'
    qc_reason       text,                               -- defect | score | resemblance | attempts
    attempts        integer     DEFAULT 1,
    created_at      timestamptz DEFAULT now(),
    -- one row per persona+scenario; lets Phase B upsert instead of duplicating
    CONSTRAINT outputs_persona_scenario_key UNIQUE (persona_id, scenario_id)
);


-- ----------------------------------------------------------------------------
-- 4. videos  -  Phase C output: one lip-synced video per scene image
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.videos (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    output_id      bigint  UNIQUE REFERENCES public.outputs(id),
    scenario_id    text,
    drive_file_id  text,                                -- Drive id of the MP4
    drive_url      text,
    prompt_used    text,
    dialogue       text,
    status         text        DEFAULT 'done',
    created_at     timestamptz DEFAULT now()
);


-- ----------------------------------------------------------------------------
-- Indexes for the lookups the pipeline runs every execution
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_country  ON public.tiktok_accounts (country);
CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_created  ON public.tiktok_accounts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_personas_account         ON public.personas (tiktok_account_id);
CREATE INDEX IF NOT EXISTS idx_outputs_persona          ON public.outputs (persona_id);
CREATE INDEX IF NOT EXISTS idx_outputs_qc_status        ON public.outputs (qc_status);
CREATE INDEX IF NOT EXISTS idx_videos_output            ON public.videos (output_id);


-- ----------------------------------------------------------------------------
-- Keep tiktok_accounts.updated_at fresh on every row update
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_tiktok_accounts_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tiktok_accounts_updated_at ON public.tiktok_accounts;
CREATE TRIGGER trg_tiktok_accounts_updated_at
    BEFORE UPDATE ON public.tiktok_accounts
    FOR EACH ROW EXECUTE FUNCTION public.set_tiktok_accounts_updated_at();


-- ----------------------------------------------------------------------------
-- Access. This project runs with RLS disabled + service-key / anon access.
-- Keep this only if you want the same posture; otherwise remove it and
-- configure proper Row Level Security policies before production.
-- ----------------------------------------------------------------------------
ALTER TABLE public.tiktok_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.personas        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outputs         DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos          DISABLE ROW LEVEL SECURITY;

GRANT ALL ON public.tiktok_accounts, public.personas, public.outputs, public.videos
    TO anon, authenticated, service_role;

-- ============================================================================
-- End of schema
-- ============================================================================
