-- ============================================================================
--  TikTok Accounts CRM  -  Supabase migration
--  Run this in the Supabase SQL editor to create the table the console reads.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.tiktok_accounts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiktok_id   text        NOT NULL UNIQUE,
    name        text        NOT NULL,
    gender      text        NOT NULL,
    country     text        NOT NULL,
    age         integer     NOT NULL CHECK (age >= 0 AND age <= 120),
    language    text        NOT NULL,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_country  ON public.tiktok_accounts (country);
CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_gender   ON public.tiktok_accounts (gender);
CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_language ON public.tiktok_accounts (language);
CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_created  ON public.tiktok_accounts (created_at DESC);

-- Keep updated_at fresh on every row update
CREATE OR REPLACE FUNCTION public.set_tiktok_accounts_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tiktok_accounts_updated_at ON public.tiktok_accounts;
CREATE TRIGGER trg_tiktok_accounts_updated_at
    BEFORE UPDATE ON public.tiktok_accounts
    FOR EACH ROW EXECUTE FUNCTION public.set_tiktok_accounts_updated_at();

-- MVP: same access posture as the existing pipeline tables (RLS disabled, anon allowed).
-- Rotate to RLS policies before going to production.
ALTER TABLE public.tiktok_accounts DISABLE ROW LEVEL SECURITY;
GRANT ALL ON public.tiktok_accounts TO anon, authenticated, service_role;
